[profile.default]
src = "src"
out = "out"
libs = ["lib"]

remappings = [
  '@ccip/contracts=lib/ccip/contracts',
  '@openzeppelin/contracts=lib/openzeppelin-contracts/contracts',
  '@chainlink/local/=lib/chainlink-local/'
]

rpc_endpoints = { sepolia-eth = "https://eth-sepolia.g.alchemy.com/v2/4kz2E-vrblsbeCQnilOWN1Y1ZCLb-hV0", arb-sepolia = "https://arb-sepolia.g.alchemy.com/v2/4kz2E-vrblsbeCQnilOWN1Y1ZCLb-hV0" }

fs_permissions = [
    { access = "read", path = "./broadcast" },
    { access = "read", path = "./reports" },
]

[invariant]
runs = 256
depth = 128
fail_on_revert = true

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
